@server = {{scheme}}://{{$processEnv COUCHDB_USER}}:{{$processEnv COUCHDB_PASSWORD}}@{{host}}
@database = test

### Deletes a database.
DELETE {{server}}/{{database}}
Accept: application/json

### Returns information about a database.
GET {{server}}/{{database}}
Accept: application/json

### Checks whether a database exists.
HEAD {{server}}/{{database}}
Accept: application/json

### Creates a new database.
PUT {{server}}/{{database}}
Accept: application/json
