// Returns meta information about the server instance.
GET {{url}}/
Accept: application/json

###

// Returns the binary content for the `favicon.ico` site icon.
GET {{url}}/favicon.ico
Accept: image/x-icon

###

// Returns a value indicating whether this server is up.
GET {{url}}/_up
Accept: application/json
